name: "Schedule"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  default:
    name: "Generate"
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
        with:
          path: checkout

      - name: "Checkout repository"
        uses: actions/checkout@v3
        with:
          repository: azure/azure-rest-api-specs
          path: specs

      - name: "Checkout repository"
        uses: actions/checkout@v3
        with:
          repository: azure/azure-resource-manager-schemas
          path: schemas

      - name: "Setup deno"
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: "Run deno"
        run: |
          deno run --allow-read --allow-write .github/scripts/main.ts schemas
        working-directory: checkout

      - name: "Configure git"
        run: |
          git config user.name "GitHub Actions"
          git config user.email "action@github.com"
        working-directory: checkout

      - name: "Push schemas"
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add ./schemas.json
            git commit -m 'gen: update files'
            git push origin main
          fi
        working-directory: checkout