name: "Schedule"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate:
    name: "Generate"
    runs-on: ubuntu-22.04
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
        with:
          path: checkout

      - name: "Checkout repository"
        uses: actions/checkout@v3
        with:
          repository: azure/azure-rest-api-specs
          path: specs

      - name: "Checkout repository"
        uses: actions/checkout@v3
        with:
          repository: azure/azure-resource-manager-schemas
          path: schemas

      - name: "Setup node"
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: "Install dependencies"
        run: |
          npm install
        working-directory: checkout

      - name: "Generate manifest"
        run: |
          npm run generate
        working-directory: checkout

      - name: "Configure git"
        run: |
          git config user.name "GitHub Actions"
          git config user.email "action@github.com"
        working-directory: checkout

      - name: "Merge schemas"
        run: |
          if [ -n "$(git status gen/ --porcelain)" ]; then
            git checkout -b gen/manifests
            git add gen/
            git commit -m 'gen: update manifests'
            git push origin gen/manifests
            gh pr create --title "gen: update manifests" --body ""
            gh pr merge gen/manifests --auto --squash
          fi
        working-directory: checkout
