name: "Generate"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate:
    name: "Generate"
    runs-on: ubuntu-22.04
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
        with:
          path: providers

      - name: "Checkout repository"
        uses: actions/checkout@v4
        with:
          repository: azure/azure-resource-manager-schemas
          path: schemas

      - name: "Setup node"
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: "Install dependencies"
        run: |
          npm install
        working-directory: providers

      - name: "Delete manifests"
        run: |
          rm -rf gen
        working-directory: providers

      - name: "Generate manifests"
        run: |
          npm run generate
        working-directory: providers

      - name: "Configure git"
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
        working-directory: providers

      - name: "Merge manifests"
        run: |
          if [ -n "$(git status gen/ --porcelain)" ]; then
            git checkout -b gen/manifests
            git add gen/
            git commit -m 'gen: update manifests'
            git push origin gen/manifests
            gh pr create --title "gen: update manifests" --body ""
            gh pr merge gen/manifests --auto --squash
          fi
        working-directory: providers

      - name: "Delete runs"
        run: |
          month=$(date -d "$(date +%Y-%m)-15 last month" '+%Y-%m')
          gh run list --created $month --json databaseId --jq '.[].databaseId' --limit 50 | xargs -I{} gh run delete {}
        working-directory: providers
