name: "Schedule"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate:
    name: "Generate"
    runs-on: ubuntu-22.04
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
        with:
          path: checkout

      - name: "Checkout repository"
        uses: actions/checkout@v3
        with:
          repository: azure/azure-rest-api-specs
          path: specs

      - name: "Checkout repository"
        uses: actions/checkout@v3
        with:
          repository: azure/azure-resource-manager-schemas
          path: schemas

      - name: "Setup deno"
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: "Run deno"
        run: |
          deno run --allow-env --allow-read --allow-write src/main.ts schemas
        working-directory: checkout

      - name: "Configure git"
        run: |
          git config user.name "GitHub Actions"
          git config user.email "action@github.com"
        working-directory: checkout

      - name: "Merge schemas"
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git checkout -b gen/schemas
            git add ./schemas.json
            git commit -m 'gen: update schemas file'
            git push origin gen/schemas
            gh pr create --title "gen: update schemas file" --body ""
            gh pr merge gen/schemas --auto --squash
          fi
        working-directory: checkout

  upload:
    name: "Upload"
    runs-on: ubuntu-22.04
    needs: generate
    if: ${{ success() }}
    permissions:
      id-token: write

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
        with:
          ref: main
          path: checkout

      - name: "Authenticate session"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: "Upload schemas"
        run: |
          az storage blob upload \
            -f schemas.json -c schemas -n providers.json \
            --account-name ${{ secrets.AZURE_STORAGE_NAME }} --auth-mode login \
            --overwrite true
        working-directory: checkout

      - name: "Purge cache"
        run: |
          az afd endpoint purge \
            -g ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --profile-name ${{ secrets.AZURE_FRONTDOOR_NAME }} \
            --endpoint-name default \
            --domains schema.ljtill.com \
            --content-paths '/*'
        working-directory: checkout